window.PSALM_1_7 = [
  // Psalm 1
  { id: 1, psalm: 1, pair: 1, upper: "不從惡人的計謀，不站罪人的道路，", lower: "不坐褻慢人的座位" },
  { id: 2, psalm: 1, pair: 2, upper: "惟喜愛耶和華的律法，", lower: "晝夜思想" },
  { id: 3, psalm: 1, pair: 3, upper: "他要像一棵樹栽在溪水旁，按時候結果子，", lower: "葉子也不枯乾" },
  { id: 4, psalm: 1, pair: 4, upper: "惡人並不是這樣，", lower: "乃像糠粃被風吹散" },
  { id: 5, psalm: 1, pair: 5, upper: "因此，當審判的時候惡人必站立不住；", lower: "罪人在義人的會中也是如此" },
  { id: 6, psalm: 1, pair: 6, upper: "因為耶和華知道義人的道路；", lower: "惡人的道路卻必滅亡" },

  // Psalm 2
  { id: 7, psalm: 2, pair: 1, upper: "外邦為什麼爭鬧？", lower: "萬民為什麼謀算虛妄的事" },
  { id: 8, psalm: 2, pair: 2, upper: "世上的君王一齊起來，臣宰一同商議，", lower: "要敵擋耶和華並他的受膏者" },
  { id: 9, psalm: 2, pair: 3, upper: "說：我們要掙開他們的捆綁，", lower: "脫去他們的繩索" },
  { id: 10, psalm: 2, pair: 4, upper: "那坐在天上的必發笑；", lower: "主必嗤笑他們" },
  { id: 11, psalm: 2, pair: 5, upper: "那時，他要在怒中責備他們，", lower: "在烈怒中驚嚇他們" },
  { id: 12, psalm: 2, pair: 6, upper: "說：我已經立我的君在錫安－", lower: "我的聖山上了" },
  { id: 13, psalm: 2, pair: 7, upper: "受膏者說：", lower: "我要傳聖旨" },
  { id: 14, psalm: 2, pair: 8, upper: "耶和華曾對我說：", lower: "你是我的兒子" },
  { id: 15, psalm: 2, pair: 9, upper: "你求我，我就將列國賜你為基業，", lower: "將地極賜你為田產" },
  { id: 16, psalm: 2, pair: 10, upper: "你必用鐵杖打破他們；", lower: "你必將他們如同窰匠的瓦器摔碎" },
  { id: 17, psalm: 2, pair: 11, upper: "現在，你們君王應當省悟！", lower: "你們世上的審判官該受管教" },
  { id: 18, psalm: 2, pair: 12, upper: "當存畏懼事奉耶和華，", lower: "又當存戰兢而快樂" },
  { id: 19, psalm: 2, pair: 13, upper: "當以嘴親子，", lower: "恐怕他發怒" },
  { id: 20, psalm: 2, pair: 14, upper: "你們便在道中滅亡，", lower: "因為他的怒氣快要發作" },
  { id: 21, psalm: 2, pair: 15, upper: "凡投靠他的，", lower: "都是有福的" },

  // Psalm 3
  { id: 22, psalm: 3, pair: 1, upper: "耶和華啊，我的敵人何其加增；", lower: "有許多人起來攻擊我" },
  { id: 23, psalm: 3, pair: 2, upper: "有許多人議論我說：", lower: "他得不著神的幫助" },
  { id: 24, psalm: 3, pair: 3, upper: "但你－耶和華是我四圍的盾牌，", lower: "是我的榮耀" },
  { id: 25, psalm: 3, pair: 4, upper: "我用我的聲音求告耶和華，", lower: "他就從他的聖山上應允我" },
  { id: 26, psalm: 3, pair: 5, upper: "我躺下睡覺，我醒著，", lower: "耶和華都保佑我" },
  { id: 27, psalm: 3, pair: 6, upper: "雖有成萬的百姓來周圍攻擊我，", lower: "我也不怕" },
  { id: 28, psalm: 3, pair: 7, upper: "因為你打了我一切仇敵的腮骨，", lower: "敲碎了惡人的牙齒" },
  { id: 29, psalm: 3, pair: 8, upper: "救恩屬乎耶和華；", lower: "願你賜福給你的百姓" },

  // Psalm 4
  { id: 30, psalm: 4, pair: 1, upper: "顯我為義的神啊，我呼籲的時候，", lower: "求你應允我" },
  { id: 31, psalm: 4, pair: 2, upper: "我在困苦中，", lower: "你曾使我寬廣" },
  { id: 32, psalm: 4, pair: 3, upper: "現在求你憐恤我，", lower: "聽我的禱告" },
  { id: 33, psalm: 4, pair: 4, upper: "你們這上流人哪，", lower: "你們將我的尊榮變為羞辱要到幾時呢" },
  { id: 34, psalm: 4, pair: 5, upper: "你們喜愛虛妄，尋找虛假，", lower: "要到幾時呢" },
  { id: 35, psalm: 4, pair: 6, upper: "你們要知道，", lower: "耶和華已經分別虔誠人歸他自己" },
  { id: 36, psalm: 4, pair: 7, upper: "我求告耶和華，", lower: "他必聽我" },
  { id: 37, psalm: 4, pair: 8, upper: "你們應當畏懼，", lower: "不可犯罪" },
  { id: 38, psalm: 4, pair: 9, upper: "在床上的時候，要心裡思想，", lower: "並要肅靜" },
  { id: 39, psalm: 4, pair: 10, upper: "當獻上公義的祭，", lower: "又當倚靠耶和華" },
  { id: 40, psalm: 4, pair: 11, upper: "有許多人說：", lower: "誰能指示我們什麼好處" },
  { id: 41, psalm: 4, pair: 12, upper: "耶和華啊，求你仰起臉來，", lower: "光照我們" },
  { id: 42, psalm: 4, pair: 13, upper: "你使我心裡快樂，", lower: "勝過那豐收五穀新酒的人" },
  { id: 43, psalm: 4, pair: 14, upper: "我必安然躺下睡覺，因為獨有你－", lower: "耶和華使我安然居住" },

  // Psalm 5
  { id: 44, psalm: 5, pair: 1, upper: "耶和華啊，求你留心聽我的言語，", lower: "顧念我的心思" },
  { id: 45, psalm: 5, pair: 2, upper: "耶和華啊，早晨你必聽我的聲音；", lower: "早晨我必向你陳明我的心意" },
  { id: 46, psalm: 5, pair: 3, upper: "因為你不是喜悅惡事的神，", lower: "惡人不能與你同居" },
  { id: 47, psalm: 5, pair: 4, upper: "狂傲人不能站在你眼前；凡作孽的，", lower: "都是你所恨惡的" },
  { id: 48, psalm: 5, pair: 5, upper: "說謊言的，", lower: "你必滅絕" },
  { id: 49, psalm: 5, pair: 6, upper: "好流人血弄詭詐的，", lower: "都為耶和華所憎惡" },
  { id: 50, psalm: 5, pair: 7, upper: "至於我，我必憑你豐盛的慈愛進入你的居所；", lower: "我必存敬畏你的心向你的聖殿下拜" },
  { id: 51, psalm: 5, pair: 8, upper: "耶和華啊，求你因我的仇敵，", lower: "憑你的公義引領我" },
  { id: 52, psalm: 5, pair: 9, upper: "因為，他們的口中沒有誠實；", lower: "他們的心裡滿有邪惡" },
  { id: 53, psalm: 5, pair: 10, upper: "他們的喉嚨是敞開的墳墓；", lower: "他們用舌頭諂媚人" },
  { id: 54, psalm: 5, pair: 11, upper: "神啊，求你定他們的罪！", lower: "願他們因自己的計謀跌倒" },
  { id: 55, psalm: 5, pair: 12, upper: "願你在他們許多的過犯中把他們逐出，", lower: "因為他們背叛了你" },
  { id: 56, psalm: 5, pair: 13, upper: "凡投靠你的，願他們喜樂，", lower: "時常歡呼" },
  { id: 57, psalm: 5, pair: 14, upper: "因為你護庇他們；", lower: "又願那愛你名的人都靠你歡欣" },
  { id: 58, psalm: 5, pair: 15, upper: "因為你必賜福與義人；耶和華啊，", lower: "你必用恩惠如同盾牌四面護衛他" },

  // Psalm 6
  { id: 59, psalm: 6, pair: 1, upper: "耶和華啊，求你不要在怒中責備我，", lower: "也不要在烈怒中懲罰我" },
  { id: 60, psalm: 6, pair: 2, upper: "耶和華啊，求你可憐我，", lower: "因為我軟弱" },
  { id: 61, psalm: 6, pair: 3, upper: "耶和華啊，求你醫治我，", lower: "因為我的骨頭發戰" },
  { id: 62, psalm: 6, pair: 4, upper: "我心也大大地驚惶。耶和華啊，", lower: "你要到幾時才救我呢" },
  { id: 63, psalm: 6, pair: 5, upper: "耶和華啊，求你轉回搭救我！", lower: "因你的慈愛拯救我" },
  { id: 64, psalm: 6, pair: 6, upper: "因為，在死地無人記念你，", lower: "在陰間有誰稱謝你" },
  { id: 65, psalm: 6, pair: 7, upper: "我每夜流淚，把床榻漂起，", lower: "把褥子濕透" },
  { id: 66, psalm: 6, pair: 8, upper: "我因憂愁眼睛乾癟，", lower: "又因我一切的敵人眼睛昏花" },
  { id: 67, psalm: 6, pair: 9, upper: "你們一切作孽的人，離開我吧！", lower: "因為耶和華聽了我哀哭的聲音" },
  { id: 68, psalm: 6, pair: 10, upper: "耶和華聽了我的懇求；", lower: "耶和華必收納我的禱告" },
  { id: 69, psalm: 6, pair: 11, upper: "我的一切仇敵都必羞愧，", lower: "大大驚惶" },
  { id: 70, psalm: 6, pair: 12, upper: "他們必要退後，", lower: "忽然羞愧" },

  // Psalm 7
  { id: 71, psalm: 7, pair: 1, upper: "求你救我脫離一切追趕我的人，", lower: "將我救拔出來" },
  { id: 72, psalm: 7, pair: 2, upper: "恐怕他們像獅子撕裂我，甚至撕碎，", lower: "無人搭救" },
  { id: 73, psalm: 7, pair: 3, upper: "耶和華－我的神啊，我若行了這事，", lower: "若有罪孽在我手裡" },
  { id: 74, psalm: 7, pair: 4, upper: "我若以惡報那與我交好的人－連那無故與我為敵的，", lower: "我也救了他" },
  { id: 75, psalm: 7, pair: 5, upper: "就任憑仇敵追趕我，", lower: "直到追上" },
  { id: 76, psalm: 7, pair: 6, upper: "將我的性命踏在地下，", lower: "使我的榮耀歸於灰塵" },
  { id: 77, psalm: 7, pair: 7, upper: "耶和華啊，求你在怒中起來，挺身而立，", lower: "抵擋我敵人的暴怒" },
  { id: 78, psalm: 7, pair: 8, upper: "求你為我興起！", lower: "你已經命定施行審判" },
  { id: 79, psalm: 7, pair: 9, upper: "願眾民的會環繞你！", lower: "願你從其上歸於高位" },
  { id: 80, psalm: 7, pair: 10, upper: "耶和華向眾民施行審判；耶和華啊，", lower: "求你按我的公義和我心中的純正判斷我" },
  { id: 81, psalm: 7, pair: 11, upper: "願惡人的惡斷絕！", lower: "願你堅立義人" },
  { id: 82, psalm: 7, pair: 12, upper: "神是我的盾牌；", lower: "他拯救心裡正直的人" },
  { id: 83, psalm: 7, pair: 13, upper: "神是公義的審判者，", lower: "又是天天向惡人發怒的神" },
  { id: 84, psalm: 7, pair: 14, upper: "若有人不回頭，", lower: "他的刀必磨快" },
  { id: 85, psalm: 7, pair: 15, upper: "弓必上弦，", lower: "預備妥當了" },
  { id: 86, psalm: 7, pair: 16, upper: "他也預備了殺人的器械；", lower: "他所射的是火箭" },
  { id: 87, psalm: 7, pair: 17, upper: "試看惡人因奸惡而劬勞，所懷的是毒害，", lower: "所生的是虛假" },
  { id: 88, psalm: 7, pair: 18, upper: "他掘了坑，又挖深了，", lower: "竟掉在自己所挖的阱裡" },
  { id: 89, psalm: 7, pair: 19, upper: "他的毒害必臨到他自己的頭上；", lower: "他的強暴必落到他自己的腦袋上" },
  { id: 90, psalm: 7, pair: 20, upper: "我要照著耶和華的公義稱謝他，", lower: "歌頌耶和華至高者的名" },
];
